# Ruby Settings
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

# Jekyll settings
markdown: rdiscount
pygments: true
permalink: pretty
auto: true
rdiscount:
  extensions: [smart]

# Site settings
sitename: Mirko Borivojevic
tagline : Professional & Reliable Web Development
email   : mirko.borivojevic@gmail.com

# Settings for Google Analytics: change UA-XXXXX-X to be your site's ID.
analytics   :
  google_tracking_id    : 'UA-34855255-1'